version: '2'

services:
  #db:
  #  image: postgres:9.6
  #  environment:
  #    POSTGRES_PASSWORD: xtramileDev
  #    POSTGRES_USER: postgres
  #  volumes:
  #    - ./docker/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  #    - ./docker/db/dumps:/dumps
  #  ports:
  #    - "15432:5432"
  nginx:
    image: nginx:1.11-alpine
    depends_on:
     - php
    ports:
      - "8005:80"
    volumes:
     - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
     - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
     - ./app/public:/srv/app/public
     - ./app/files:/srv/app/files
  php:
    build: .
    #depends_on:
    #  - db
    #environment:
    #  SYMFONY_ENV: dev
    volumes:
      - ./app:/srv/app
    dns: 8.8.8.8

volumes:
  db-data: {}
